/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TokoRoti;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author HP
 */
/**
 * Creates new form DataRotii
 */

public class DataRoti extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;

    private static final String URL = "jdbc:postgresql://localhost:5432/PBO4";
    static final String USER = "postgres";
    private static final String PASSWORD = "BISMILLAH";
    
    String idkueLama, namakueLama, hargaLama, stockLama;


    public DataRoti() {
        initComponents();
        connect();
        showTable();
        
     tabeldataroti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tabeldataroti.getSelectedRow();

                idkueLama = tabeldataroti.getValueAt(row, 0).toString();
                namakueLama = tabeldataroti.getValueAt(row, 1).toString();
                hargaLama = tabeldataroti.getValueAt(row, 2).toString();
                stockLama = tabeldataroti.getValueAt(row, 3).toString();

                textidkue.setText(idkueLama);
                textnamakue.setText(namakueLama);
                textharga.setText(hargaLama);
                textstock.setText(stockLama);
            }
        });
    }
   

    public void connect() {
        try {
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            stmt = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public void bersih() {
        textidkue.setText("");
        textnamakue.setText("");
        textharga.setText("");
        textstock.setText("");
    }

    public void showTable() {
        try {
            String sql = "SELECT * FROM tokoroti ORDER BY id_kue";
            ResultSet rs = stmt.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"idkue", "nama kue", "harga", "stock"}, 0
            );

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_kue"),
                    rs.getString("nama_kue"),
                    rs.getString("harga"),
                    rs.getString("stock")
                });
            }

            tabeldataroti.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_idroti = new javax.swing.JLabel();
        textidkue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textnamakue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textstock = new javax.swing.JTextField();
        Button_tambah = new javax.swing.JToggleButton();
        Button_perbarui = new javax.swing.JToggleButton();
        Button_hapus = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldataroti = new javax.swing.JTable();
        Button_bersih = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_idroti.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel_idroti.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_idroti.setText("Id Roti");

        textidkue.setBackground(new java.awt.Color(204, 255, 255));
        textidkue.setForeground(new java.awt.Color(0, 0, 0));
        textidkue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidkueActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Roti");

        textnamakue.setBackground(new java.awt.Color(204, 255, 255));
        textnamakue.setForeground(new java.awt.Color(0, 0, 0));
        textnamakue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamakueActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Harga");

        textharga.setBackground(new java.awt.Color(204, 255, 255));
        textharga.setForeground(new java.awt.Color(0, 0, 0));
        textharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Stock");

        textstock.setBackground(new java.awt.Color(204, 255, 255));
        textstock.setForeground(new java.awt.Color(0, 0, 0));
        textstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstockActionPerformed(evt);
            }
        });

        Button_tambah.setBackground(new java.awt.Color(0, 204, 204));
        Button_tambah.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        Button_tambah.setForeground(new java.awt.Color(0, 0, 0));
        Button_tambah.setText("TAMBAH");
        Button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_tambahActionPerformed(evt);
            }
        });

        Button_perbarui.setBackground(new java.awt.Color(0, 204, 204));
        Button_perbarui.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        Button_perbarui.setForeground(new java.awt.Color(0, 0, 0));
        Button_perbarui.setText("PERBARUI");
        Button_perbarui.setActionCommand("perbarui");
        Button_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_perbaruiActionPerformed(evt);
            }
        });

        Button_hapus.setBackground(new java.awt.Color(0, 204, 204));
        Button_hapus.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        Button_hapus.setForeground(new java.awt.Color(0, 0, 0));
        Button_hapus.setText("HAPUS");
        Button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_hapusActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/bakery_9102671 (3).png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("DATA ROTI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabeldataroti.setBackground(new java.awt.Color(204, 255, 255));
        tabeldataroti.setForeground(new java.awt.Color(0, 0, 0));
        tabeldataroti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_Roti", "Nama_Roti", "Harga", "Stok"
            }
        ));
        tabeldataroti.setGridColor(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(tabeldataroti);

        Button_bersih.setBackground(new java.awt.Color(0, 204, 204));
        Button_bersih.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        Button_bersih.setForeground(new java.awt.Color(0, 0, 0));
        Button_bersih.setText("BERSIH");
        Button_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_bersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel_idroti))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textidkue)
                                    .addComponent(textnamakue)
                                    .addComponent(textstock)
                                    .addComponent(textharga)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Button_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_perbarui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidkue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idroti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnamakue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textstock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_perbarui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Button_bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textnamakueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamakueActionPerformed

    }//GEN-LAST:event_textnamakueActionPerformed

    private void textstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstockActionPerformed

    private void textidkueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidkueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidkueActionPerformed

    private void texthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaActionPerformed

    private void Button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_tambahActionPerformed
        if (textidkue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi semua data !");
        } else if (textnamakue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi semua data !");
        } else if (textharga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi semua data !");
        } else if (textstock.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " isi semua data !");
        } else {
            try {
                String sql = "INSERT INTO tokoroti (id_kue, nama_kue, harga, stock) VALUES (?,?,?,?)";
                var ps = conn.prepareStatement(sql);
                ps.setString(1, textidkue.getText());
                ps.setString(2, textnamakue.getText());
                ps.setInt(3, Integer.parseInt(textharga.getText()));
                ps.setInt(4, Integer.parseInt(textstock.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "data berhasil disimpan !");
                showTable();
                bersih();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_Button_tambahActionPerformed

    private void Button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_hapusActionPerformed
        if (textidkue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textnamakue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textharga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textstock.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else {
        }
        try {
            String sql = "DELETE FROM tokoroti WHERE id_kue=?";
            var ps = conn.prepareStatement(sql);
            ps.setString(1, textidkue.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            showTable();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error delete: " + e.getMessage());
        }
    }//GEN-LAST:event_Button_hapusActionPerformed

    private void Button_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_bersihActionPerformed
        bersih();
    }//GEN-LAST:event_Button_bersihActionPerformed

    private void Button_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_perbaruiActionPerformed
       if (textidkue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textnamakue.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textharga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textstock.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else {
        try {
                String sql = "UPDATE tokoroti SET id_kue=?, nama_kue=?, harga=?, stock=? "
                        + "WHERE id_kue=? AND nama_kue=? AND harga=? AND stock=?";

                var ps = conn.prepareStatement(sql);

                ps.setString(1, textidkue.getText());
                ps.setString(2, textnamakue.getText());
                ps.setInt(3, Integer.parseInt(textharga.getText()));
                ps.setInt(4, Integer.parseInt(textstock.getText()));
                
                ps.setString(5, idkueLama);
                ps.setString(6, namakueLama);
                ps.setInt(7, Integer.parseInt(hargaLama));
                ps.setInt(8, Integer.parseInt(stockLama));
           

                int rows = ps.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                    showTable();
                    bersih();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_Button_perbaruiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataRoti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button_bersih;
    private javax.swing.JToggleButton Button_hapus;
    private javax.swing.JToggleButton Button_perbarui;
    private javax.swing.JToggleButton Button_tambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_idroti;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldataroti;
    private javax.swing.JTextField textharga;
    private javax.swing.JTextField textidkue;
    private javax.swing.JTextField textnamakue;
    private javax.swing.JTextField textstock;
    // End of variables declaration//GEN-END:variables
}
